#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# .asf.yml -- ASF infra services configuration
#

# GitHub Action notifications, see 
# https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file
#
# However, according to discussion with Humbedooh on Slack the-asf#Infra,
# it require a r/w Git repository, so the below doesn't work.
#
# Humbedooh has kindly helped us hard-code a one-off notification which
# doesn't rely on .asf.yaml.
#
# Commenting out, but keeping in place as a sticky-note for future changes.
#
# For reference, this is the hard-coded configuration:
#notifications:
#  jobs: notifications@subversion.apache.org
