#!/bin/sh
#
# PROVIDE: svnwcsub
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="svnwcsub"
rcvar=`set_rcvar`

load_rc_config $name

#
# DO NOT CHANGE THESE DEFAULT VALUES HERE
# SET THEM IN THE /etc/rc.conf FILE
#
svnwcsub_enable=${svnwcsub_enable-"NO"}
svnwcsub_user=${svnwcsub_user-"svnwc"}
svnwcsub_group=${svnwcsub_group-"svnwc"}
svnwcsub_pidfile=${svnwcsub_pidfile-"/var/run/svnwcsub/svnwcsub.pub"}
svnwcsub_env="PYTHON_EGG_CACHE"
svnwcsub_cmd_int=${svnwcsub_cmd_int-"python"}
pidfile="${svnwcsub_pidfile}"

export PYTHON_EGG_CACHE="/var/run/svnwcsub"

command="/usr/local/svnpubsub/svnwcsub.py"
command_interpreter="/usr/local/bin/${svnwcsub_cmd_int}"
command_args="--daemon \
              --logfile=/var/log/svnwcsub.log \
              --pidfile=${pidfile} \
              --uid=${svnwcsub_user} --gid=${svnwcsub_group} \
              --umask=002 /etc/svnwcsub.conf"

run_rc_command "$1"
