# /****************************************************************
# Copyright (C) Lucent Technologies 1997
# All Rights Reserved
# 
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby
# granted, provided that the above copyright notice appear in all
# copies and that both that the copyright notice and this
# permission notice and warranty disclaimer appear in supporting
# documentation, and that the name Lucent Technologies or any of
# its entities not be used in advertising or publicity pertaining
# to distribution of the software without specific, written prior
# permission.
# 
# LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
# IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
# SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
# IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
# THIS SOFTWARE.
# ****************************************************************/

CC = cl /c
CFLAGS = /nologo /W3 /O2 /MT /D "NDEBUG" /D "MSDOS" /D "_CONSOLE" /D "_CRT_SECURE_NO_WARNINGS"

LINK = link
LFLAGS = /nologo /subsystem:console /machine:I386
LIBS = setargv.obj oldnames.lib

YACC = bison -y
YFLAGS = -d

OFILES = b.obj main.obj parse.obj proctab.obj tran.obj lib.obj run.obj \
	lex.obj missing95.obj

SOURCE = awk.h ytab.c ytab.h proto.h awkgram.y lex.c b.c main.c \
	maketab.c parse.c lib.c run.c tran.c proctab.c missing95.c

LISTING = awk.h proto.h awkgram.y lex.c b.c main.c maketab.c parse.c \
	lib.c run.c tran.c missing95.c

SHIP = README FIXES $(SOURCE) ytabc.bak ytabh.bak makefile makefile.win \
	vcvars32.bat buildwin.bat awk.1

awk.exe:	ytab.obj $(OFILES)
	$(LINK) $(LFLAGS) -out:awk.exe ytab.obj $(OFILES) $(LIBS)

$(OFILES):	awk.h ytab.h proto.h

ytab.obj:	awk.h proto.h awkgram.y
	$(YACC) $(YFLAGS) awkgram.y
	move /y y.tab.c ytab.c
	move /y y.tab.h ytab.h
	$(CC) $(CFLAGS) ytab.c

proctab.c:	maketab.exe
	maketab.exe >proctab.c

maketab.exe:	ytab.h maketab.obj
	$(LINK) $(LFLAGS) maketab.obj $(LIBS)

bundle:
	@copy /y ytab.h ytabh.bak
	@copy /y ytab.c ytabc.bak
	@bundle $(SHIP)

tar:
	@copy ytab.h ytabh.bak
	@copy ytab.c ytabc.bak
	@bundle $(SHIP) >awk.shar
	@tar cf awk.tar $(SHIP)
	gzip awk.tar
	ls -l awk.tar.gz
	@zip awk.zip $(SHIP)
	ls -l awk.zip

names:
	@echo $(LISTING)

clean:
	del /f a.out *.o *.obj maketab maketab.exe *.bb *.bbg *.da *.gcov *.gcno *.gcda # proctab.c
