# todo: eventually this will be replaced with Makefile.in.

default: vdelta

# Look, I just wanna compile my test code *now*... We'll clean up later.
vdelta:
	gcc -c ../svn_subr/alloc.c
	gcc -c hash.c
