import unittest
import svn.delta

# Test case for svn.delta
class DeltaTestCase(unittest.TestCase):

  def testTxWindowHandler(self):
    """Make sure that the tx_invoke_window_handler function was
       generated by header_wrappers.py"""
    return self.assertNotEqual(svn.delta.tx_invoke_window_handler, None)

def suite():
  return unittest.makeSuite(DeltaTestCase, 'test')

if __name__ == '__main__':
  runner = unittest.TextTestRunner()
  runner.run(suite());
