@node Protocol
@chapter Protocol

The Subversion client library @code{libsvn_ra_dav} uses the @emph{Neon}
library to generate WebDAV DeltaV requests and sends them to a
"Subversion-aware" Apache server.

This Apache server is running @emph{mod_dav} and @emph{mod_dav_svn},
which translates the requests into Subversion filesystem calls.  

For more info, @xref{Network Layer}.

For a detailed description of exactly how Greg Stein
<@email{gstein@@lyra.org}> is mapping the WebDAV DeltaV spec to
Subversion, see his paper:
@uref{http://svn.collab.net/repos/svn/trunk/www/webdav-usage.html}

For more information on WebDAV and the DeltaV extensions, see
@uref{http://www.webdav.org} and @uref{http://www.webdav.org/deltav}.

For more information on @emph{Neon}, see
@uref{http://www.webdav.org/neon}.

