@node Protocol
@chapter Protocol

The network layer of Subversion is not yet defined.

@itemize @bullet
@item
  For the initial ``proof-of-concept'' release, there will be no network
layer at all.  The Subversion client libraries will link directly
against the Subversion server libraries.  This will allow identical APIs
to match up one-to-one for testing.
@item
  For the first ``real'' release, we will use Apache as a kind of
generic, all-purpose server.  The client API calls will be translated
into custom HTTP methods (possibly WebDAV methods); a custom Apache
module will interpret them and make calls into the Subversion server
libraries.  For details, @xref{Network Layer}.
@end itemize

