#!/bin/bash
USAGE="Fix some kinds of corruption in a Subversion repository
by running './fixer/fix-rev.py' on each revision.
Usage: $0 REPO-DIR START-REV"

REPO_DIR="$1"
START_REV="$2"

if [ ! -d "$REPO_DIR" ] || [ "$START_REV" = "" ]; then
  echo "$USAGE" >&2
  exit 1
fi

YOUNGEST="$(svnlook youngest "$REPO_DIR")"

if [ "$YOUNGEST" = "" ]; then
  echo "$0: error running 'svnlook youngest $REPO_DIR'"
  exit 1
fi

echo "Verifying revisions $START_REV through $YOUNGEST."

for ((REV=$START_REV; REV <= $YOUNGEST; REV++)); do
  echo "=== r$REV"
  ./fixer/fix-rev.py "$REPO_DIR" "$REV"
done
