/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tigris_subversion_javahl_SVNAdmin */

#ifndef _Included_org_tigris_subversion_javahl_SVNAdmin
#define _Included_org_tigris_subversion_javahl_SVNAdmin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    ctNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_ctNative
  (JNIEnv *, jobject);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    create
 * Signature: (Ljava/lang/String;ZZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_create
  (JNIEnv *, jobject, jstring, jboolean, jboolean, jstring);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    deltify
 * Signature: (Ljava/lang/String;Lorg/tigris/subversion/javahl/Revision;Lorg/tigris/subversion/javahl/Revision;)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_deltify
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    dump
 * Signature: (Ljava/lang/String;Lorg/tigris/subversion/javahl/OutputInterface;Lorg/tigris/subversion/javahl/OutputInterface;Lorg/tigris/subversion/javahl/Revision;Lorg/tigris/subversion/javahl/Revision;Z)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_dump
  (JNIEnv *, jobject, jstring, jobject, jobject, jobject, jobject, jboolean);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    hotcopy
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_hotcopy
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    listDBLogs
 * Signature: (Ljava/lang/String;Lorg/tigris/subversion/javahl/SVNAdmin$MessageReceiver;)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_listDBLogs
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    listUnusedDBLogs
 * Signature: (Ljava/lang/String;Lorg/tigris/subversion/javahl/SVNAdmin$MessageReceiver;)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_listUnusedDBLogs
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    load
 * Signature: (Ljava/lang/String;Lorg/tigris/subversion/javahl/InputInterface;Lorg/tigris/subversion/javahl/OutputInterface;ZZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_load
  (JNIEnv *, jobject, jstring, jobject, jobject, jboolean, jboolean, jstring);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    lstxns
 * Signature: (Ljava/lang/String;Lorg/tigris/subversion/javahl/SVNAdmin$MessageReceiver;)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_lstxns
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    recover
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_recover
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    rmtxns
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_rmtxns
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    setLog
 * Signature: (Ljava/lang/String;Lorg/tigris/subversion/javahl/Revision;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_setLog
  (JNIEnv *, jobject, jstring, jobject, jstring, jboolean);

/*
 * Class:     org_tigris_subversion_javahl_SVNAdmin
 * Method:    verify
 * Signature: (Ljava/lang/String;Lorg/tigris/subversion/javahl/OutputInterface;Lorg/tigris/subversion/javahl/Revision;Lorg/tigris/subversion/javahl/Revision;)V
 */
JNIEXPORT void JNICALL Java_org_tigris_subversion_javahl_SVNAdmin_verify
  (JNIEnv *, jobject, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
