#!/usr/bin/perl

# svn-clean - Wipes out unversioned files from SVN working copy.
# Copyright (C) 2004  Simon Perreault
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# To contact the author, send email to nomis80@nomis80.org or send
# paper mail to:
#
# Simon Perreault
# 2955 de la Verdure, #303
# Ste-Foy, QC, Canada
# G1X 4R5

use strict;
use warnings;
use File::Path;

# Default target is the current directory.
@ARGV = (".") if not @ARGV;

# Main file-wiping loop.
foreach (@ARGV) {
    open SVN, "-|", qw(svn status --no-ignore -v), $_
      or die "Can't call program \"svn\": $!\n";
    while (<SVN>) {
        if (/^[\?I]\s+(.+)$/) {
            rmtree( $1, 1, 1 );
        }
    }
}
