/*
 * compress-test.c:  tests the compression functions.
 *
 * ====================================================================
 *    Licensed to the Apache Software Foundation (ASF) under one
 *    or more contributor license agreements.  See the NOTICE file
 *    distributed with this work for additional information
 *    regarding copyright ownership.  The ASF licenses this file
 *    to you under the Apache License, Version 2.0 (the
 *    "License"); you may not use this file except in compliance
 *    with the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing,
 *    software distributed under the License is distributed on an
 *    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *    KIND, either express or implied.  See the License for the
 *    specific language governing permissions and limitations
 *    under the License.
 * ====================================================================
 */

#include <apr_time.h>

#include "private/svn_subr_private.h"
#include "../svn_test.h"
#include "svn_error.h"
#include "svn_string.h"


static const char uncompressed[] =
  "aaaabbbbccccaaaaccccbbbbaaaabbbb"
  "aaaabbbbccccaaaaccccbbbbaaaabbbb"
  "aaaabbbbccccaaaaccccbbbbaaaabbbb";
static const apr_size_t uncompressed_size = sizeof(uncompressed);

static const char compressed_block[] =
  "\x61\xc0\x61\x61\x61\x61\x62\x62\x62\x62\x63\x63\x63\x63\x0c\x00\x00\x08"
  "\x00\x00\x10\x00\x00\x0c\x00\x08\x08\x00\x00\x18\x00\x00\x14\x00\x00\x08"
  "\x00\x08\x18\x00\x00\x14\x00\x00\x10\x00\x00\x18\x00\x00\x0c\x00\x00\x08"
  "\x00\x00\x10\x00\x90\x61\x61\x61\x61\x62\x62\x62\x62";
static const apr_size_t compressed_block_size = sizeof(compressed_block);

/* Generated by piping the uncompressed data through lz4:
 *   echo -n "..." | lz4 --best --no-frame-crc -BD -BX \
 *       | hexdump -v -e '/1 "\\x%02x"'
 */
static const char compressed_frame[] =
  "\x04\x22\x4d\x18\x70\x40\xad\x22\x00\x00\x00\xc0\x61\x61\x61\x61\x62\x62"
  "\x62\x62\x63\x63\x63\x63\x0c\x00\x00\x08\x00\x00\x10\x00\x04\x18\x00\x0f"
  "\x20\x00\x28\x50\x61\x62\x62\x62\x62\x78\x16\xca\xbf\x00\x00\x00\x00";
static const apr_size_t compressed_frame_size = sizeof(compressed_frame) - 1;

/* Generated with:
 *   echo -n "" | lz4 --best --no-frame-crc -BD -BX \
 *       | hexdump -v -e '/1 "\\x%02x"'
 */
static const char empty_frame[] =
  "\x04\x22\x4d\x18\x70\x40\xad\x00\x00\x00\x00";
static const apr_size_t empty_frame_size = sizeof(empty_frame) - 1;


static svn_error_t *
test_decompress_lz4(apr_pool_t *pool)
{
  svn_stringbuf_t *decompressed = svn_stringbuf_create_empty(pool);

  SVN_ERR(svn__decompress_lz4(compressed_block, compressed_block_size,
                              decompressed, uncompressed_size));
  SVN_TEST_INT_ASSERT(decompressed->len, uncompressed_size);
  SVN_TEST_STRING_ASSERT(decompressed->data, uncompressed);

  return SVN_NO_ERROR;
}

static svn_error_t *
test_compress_lz4(apr_pool_t *pool)
{
  svn_stringbuf_t *compressed = svn_stringbuf_create_empty(pool);
  SVN_ERR(svn__compress_lz4(uncompressed, uncompressed_size, compressed));
  SVN_TEST_INT_ASSERT(compressed->len, compressed_block_size);
  SVN_TEST_BUFFER_ASSERT(compressed->data, compressed_block, compressed->len);

  return SVN_NO_ERROR;
}

static svn_error_t *
de_compress_lz4(const char input[], apr_size_t length, apr_pool_t *pool)
{
  svn_stringbuf_t *compressed = svn_stringbuf_create_empty(pool);
  svn_stringbuf_t *decompressed = svn_stringbuf_create_empty(pool);

  SVN_ERR(svn__compress_lz4(input, length, compressed));
  SVN_ERR(svn__decompress_lz4(compressed->data, compressed->len,
                              decompressed, length));
  SVN_TEST_INT_ASSERT(decompressed->len, length);
  SVN_TEST_BUFFER_ASSERT(decompressed->data, input, decompressed->len);

  return SVN_NO_ERROR;
}

static svn_error_t *
test_compress_lz4_random(apr_pool_t *pool)
{
  const apr_size_t length = 2047;
  const apr_uint32_t initial_seed = (apr_uint32_t)apr_time_now();
  apr_uint32_t seed = initial_seed;
  void *data = svn_test_make_random_data(&seed, length, pool);
  svn_error_t *err = de_compress_lz4(data, length, pool);
  if (err)
    fprintf(stderr, "SEED: %lu\n", (unsigned long) initial_seed);
  return err;
}

static svn_error_t *
test_compress_lz4_empty(apr_pool_t *pool)
{
  return de_compress_lz4("", 0, pool);
}


static svn_error_t *
compress_lz4_stream(svn_stringbuf_t **compressed,
                    const char *input, apr_size_t length,
                    svn_boolean_t stable, apr_pool_t *pool)
{
  const apr_size_t block_size = 2 * svn_lz4__header_size_max();

  svn_stringbuf_t *buf = svn_stringbuf_create_empty(pool);
  svn_lz4__compress_ctx_t *cctx;
  apr_size_t input_read = 0;
  apr_size_t output_size;

  SVN_ERR(svn_lz4__compress_create(&cctx, stable, pool));
  while (input_read < length)
    {
      const apr_size_t remaining = length - input_read;
      const apr_size_t input_size = (remaining > block_size
                                     ? block_size : remaining);

      output_size = svn_lz4__compress_bound(cctx, input_size);
      svn_stringbuf_ensure(buf, buf->len + output_size);
      SVN_ERR(svn_lz4__compress_update(&output_size, cctx,
                                       buf->data + buf->len, output_size,
                                       input, input_size));
      buf->len += output_size;
      input_read += input_size;
      input += input_size;
    }

  output_size = svn_lz4__compress_bound(cctx, 0);
  svn_stringbuf_ensure(buf, buf->len + output_size);
  SVN_ERR(svn_lz4__compress_end(&output_size, cctx,
                                buf->data + buf->len, output_size));
  buf->len += output_size;

  *compressed = buf;
  return SVN_NO_ERROR;
}

static svn_error_t *
decompress_lz4_stream(svn_stringbuf_t **decompressed,
                      const char *input, apr_size_t length,
                      svn_boolean_t stable, apr_pool_t *pool)
{
  const apr_size_t block_size = 2 * svn_lz4__header_size_max();

  svn_stringbuf_t *buf = svn_stringbuf_create_empty(pool);
  svn_lz4__decompress_ctx_t *dctx;
  apr_size_t input_read = 0;
  apr_size_t size_hint = 1;

  SVN_ERR(svn_lz4__decompress_create(&dctx, stable, pool));
  while (input_read <= length && size_hint > 0)
    {
      const apr_size_t remaining = length - input_read;
      apr_size_t input_size = (remaining > block_size
                               ? block_size : remaining);
      apr_size_t output_size = block_size;

      svn_stringbuf_ensure(buf, buf->len + output_size);
      SVN_ERR(svn_lz4__decompress(&size_hint, dctx,
                                  buf->data + buf->len, &output_size,
                                  input, &input_size));
      buf->len += output_size;
      input_read += input_size;
      input += input_size;
    }
  SVN_TEST_INT_ASSERT(size_hint, 0);
  SVN_TEST_INT_ASSERT(input_read, length);

  *decompressed = buf;
  return SVN_NO_ERROR;
}

static svn_error_t *
decompress_lz4_frame(svn_boolean_t stable, apr_pool_t *pool)
{
  svn_stringbuf_t *decompressed;

  SVN_ERR(decompress_lz4_stream(&decompressed,
                                compressed_frame,
                                compressed_frame_size,
                                stable, pool));

  /* Make sure the output buffer is NUL-terminated */
  svn_stringbuf_appendbyte(decompressed, '\0');
  SVN_TEST_STRING_ASSERT(decompressed->data, uncompressed);

  return SVN_NO_ERROR;
}

static svn_error_t *
test_decompress_lz4_frame(apr_pool_t *pool)
{
  return decompress_lz4_frame(FALSE, pool);
}

static svn_error_t *
test_decompress_lz4_frame_stable(apr_pool_t *pool)
{
  return decompress_lz4_frame(TRUE, pool);
}

static svn_error_t *
test_decompress_lz4_frame_empty(apr_pool_t *pool)
{
  svn_stringbuf_t *decompressed;
  SVN_ERR(decompress_lz4_stream(&decompressed,
                                empty_frame, empty_frame_size,
                                FALSE, pool));
  SVN_TEST_INT_ASSERT(decompressed->len, 0);
  return SVN_NO_ERROR;
}

static svn_error_t *
de_compress_lz4_stream(const char *input, apr_size_t length,
                       svn_boolean_t stable, apr_pool_t *pool)
{
  svn_stringbuf_t *compressed;
  svn_stringbuf_t *decompressed;

  SVN_ERR(compress_lz4_stream(&compressed, input, length, stable, pool));
  SVN_ERR(decompress_lz4_stream(&decompressed,
                                compressed->data, compressed->len,
                                stable, pool));
  SVN_TEST_INT_ASSERT(decompressed->len, length);
  SVN_TEST_BUFFER_ASSERT(decompressed->data, input, decompressed->len);
  return SVN_NO_ERROR;
}

static svn_error_t *
de_compress_lz4_frame_random(svn_boolean_t stable, apr_pool_t *pool)
{
  const apr_size_t length = 2047;
  const apr_uint32_t initial_seed = (apr_uint32_t)apr_time_now();
  apr_uint32_t seed = initial_seed;
  void *data = svn_test_make_random_data(&seed, length, pool);
  svn_error_t *err = de_compress_lz4_stream(data, length, stable, pool);
  if (err)
    fprintf(stderr, "SEED: %lu\n", (unsigned long) initial_seed);
  return err;
}

static svn_error_t *
test_compress_lz4_frame_random(apr_pool_t *pool)
{
  return de_compress_lz4_frame_random(FALSE, pool);
}

static svn_error_t *
test_compress_lz4_frame_random_stable(apr_pool_t *pool)
{
  return de_compress_lz4_frame_random(TRUE, pool);
}

static svn_error_t *
test_compress_lz4_frame_no_header_space(apr_pool_t *pool)
{
  const apr_size_t block_size = svn_lz4__header_size_max() - 1;
  svn_stringbuf_t *compressed = svn_stringbuf_create_ensure(block_size, pool);
  svn_lz4__compress_ctx_t *cctx;
  apr_size_t length;
  svn_error_t *err;

  SVN_ERR(svn_lz4__compress_create(&cctx, FALSE, pool));

  /* First update checks there's space for the frame header
     before calling LZ4F_compressBegin(), and we just made
     the space too small. */
  err = svn_lz4__compress_update(&length, cctx,
                                 compressed->data, block_size,
                                 "", 0);
  svn_error_clear(err);
  SVN_TEST_ASSERT(err != SVN_NO_ERROR);
  return SVN_NO_ERROR;
}


static int max_threads = -1;

static struct svn_test_descriptor_t test_funcs[] =
{
  SVN_TEST_NULL,
  SVN_TEST_PASS2(test_decompress_lz4,
                 "test svn__decompress_lz4()"),
  SVN_TEST_PASS2(test_compress_lz4,
                 "test svn__compress_lz4()"),
  SVN_TEST_PASS2(test_compress_lz4_random,
                 "test svn__de/compress_lz4() with random input"),
  SVN_TEST_PASS2(test_compress_lz4_empty,
                 "test svn__de/compress_lz4() with empty input"),
  SVN_TEST_PASS2(test_decompress_lz4_frame,
                 "test svn_lz4__decompress()"),
  SVN_TEST_PASS2(test_decompress_lz4_frame_stable,
                 "test svn_lz4__decompress() with stable output"),
  SVN_TEST_PASS2(test_decompress_lz4_frame_empty,
                 "test svn_lz4__decompress() with empty input"),
  SVN_TEST_PASS2(test_compress_lz4_frame_random,
                 "test svn_lz4__de/compress() with random input"),
  SVN_TEST_PASS2(test_compress_lz4_frame_random_stable,
                 "test svn_lz4__de/compress() with stable output"),
  SVN_TEST_PASS2(test_compress_lz4_frame_no_header_space,
                 "test svn_lz4__compress() with small buffer"),
  SVN_TEST_NULL
};

SVN_TEST_MAIN
